version: '3.8'
services:
  blog-ui:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
      - /app/node_modules/
      - /app/.next/
    command: npm run serve
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production