version: '3.8'
services:
  blog-ui:
    build:
      context: ./
      target: runner
    command: npm run serve
    pull_policy: build
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production